version: "3.7"

services:
  database:
    image: postgres
    container_name: feedget-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=feedget
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: feedget-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database

volumes:
  pgdata:
    driver: local